/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "",
  "description": "",
  "base": "/",
  "headTags": [],
  "pages": [
    {
      "title": "sum",
      "frontmatter": {},
      "regularPath": "/Basic/sum.html",
      "relativePath": "Basic/sum.md",
      "key": "v-caf993f0",
      "path": "/Basic/sum.html",
      "headers": [
        {
          "level": 2,
          "title": "sum(a,b)",
          "slug": "sum-a-b"
        },
        {
          "level": 3,
          "title": "描述",
          "slug": "描述"
        },
        {
          "level": 3,
          "title": "参数",
          "slug": "参数"
        },
        {
          "level": 3,
          "title": "返回值",
          "slug": "返回值"
        },
        {
          "level": 3,
          "title": "示例",
          "slug": "示例"
        }
      ]
    },
    {
      "title": "Home",
      "frontmatter": {
        "home": true,
        "heroImage": "https://s3.bmp.ovh/imgs/2022/12/02/bc7428e3916c3a4c.jpg",
        "heroText": "51job frontend business utils",
        "tagline": "简单易用，合作共建",
        "actionText": "快速上手→",
        "actionLink": "/Basic/sum",
        "features": [
          {
            "title": "融入现有部门基建",
            "details": "使用 monorepo 管理多项目，并提供详尽的文档指引。"
          },
          {
            "title": "按需引入",
            "details": "根据业务项目需求，实现按需引入，以减少打包体积并优化性能。"
          },
          {
            "title": "合作共建",
            "details": "业务组共建，避免重复造轮子；在提交前进行严格校验，包括 TypeScript 类型检查、Jest 单元测试和用例校验；使用 changeset 管理版本。"
          }
        ],
        "footer": "51job 前端部门出品©2024"
      },
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-51abfa33",
      "path": "/"
    },
    {
      "title": "axiosHandle",
      "frontmatter": {},
      "regularPath": "/Request/axiosHandle.html",
      "relativePath": "Request/axiosHandle.md",
      "key": "v-239e3708",
      "path": "/Request/axiosHandle.html",
      "headers": [
        {
          "level": 3,
          "title": "描述",
          "slug": "描述"
        }
      ]
    }
  ],
  "themeConfig": {}
}